### ISSUE TITLE
Channel integration

### ISSUE THREAD

**Issue by tommyhaggerty** [arkie/hackyslack2#21]
Hey,
Nice app, it is a lot of fun. Would you be able to add integration to allow it to only deployed to a specific channel like many other apps?

Thanks!

**Comment by arkie** [comment]
It should only respond to /slash commands wherever they're entered. Do you
mean limiting to a certain channel that it would respond in?

**Comment by tommyhaggerty** [comment]
Yeah, sorry I wasn't more clear. That is correct. Other apps have some functionality to only allow the commands in a selected channel. 
Thanks for the response. 
Tommy Haggerty


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Jon Caldwell <notifications@github.com> Date: 5/15/17  22:02  (GMT-07:00) To: arkie/hackyslack2 <hackyslack2@noreply.github.com> Cc: Tommy Haggerty <tommy.haggerty@gmail.com>, Author <author@noreply.github.com> Subject: Re: [arkie/hackyslack2] Channel integration (#21) 
It should only respond to /slash commands wherever they're entered. Do you

mean limiting to a certain channel that it would respond in?



On Mon, 15 May 2017 at 14:50 Tommy Haggerty <notifications@github.com>

wrote:

**Comment by arkie** [comment]
Based on clicking around https://api.slack.com/docs/slack-button it seems like the channel permissions are more for incoming webhook based apps instead of command ones? I'm not sure there's a good way to have the normal install for the command while also optionally allowing limiting to one channel, so closing out for now, but feel free to reopen with more examples or relevant docs / explanation.
